/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseLayers: typeof import('./src/components/toolbar/plugins/BaseLayers.vue')['default']
    CesiumDrawTool: typeof import('./src/components/toolbar/plugins/CesiumDrawTool.vue')['default']
    CesiumMeasureTool: typeof import('./src/components/toolbar/plugins/CesiumMeasureTool.vue')['default']
    CesiumTestXGAnlysis: typeof import('./src/components/CesiumXGAnalysis/CesiumTestXGAnlysis.vue')['default']
    CesiumThemeSwitchTool: typeof import('./src/components/toolbar/plugins/CesiumThemeSwitchTool.vue')['default']
    CesiumZoomInOrOut: typeof import('./src/components/toolbar/plugins/CesiumZoomInOrOut.vue')['default']
    ElImage: typeof import('element-ui/lib/image')['default']
    ElOption: typeof import('element-ui/lib/option')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElSlider: typeof import('element-ui/lib/slider')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    ElTooltip: typeof import('element-ui/lib/tooltip')['default']
    ElTree: typeof import('element-ui/lib/tree')['default']
    ImageDownloader: typeof import('./src/components/ImageDownloader/ImageDownloader.vue')['default']
    ImageTimeLine: typeof import('./src/components/toolbar/plugins/ImageTimeLine.vue')['default']
    IQuery: typeof import('./src/components/iSelect/iQuery.vue')['default']
    ISelect: typeof import('./src/components/iSelect/iSelect.vue')['default']
    LayerIQuery: typeof import('./src/components/toolbar/plugins/LayerIQuery.vue')['default']
    Map: typeof import('./src/components/map/map.vue')['default']
    Map2D: typeof import('./src/components/map/map2D.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeLine: typeof import('./src/components/timePlayer/timeLine.vue')['default']
    TimePlayer: typeof import('./src/components/timePlayer/index.vue')['default']
    Toolbar2: typeof import('./src/components/toolbar/toolbar2.vue')['default']
    VueCesiumShutter: typeof import('./src/components/toolbar/plugins/VueCesiumShutter.vue')['default']
  }
}
